main: main.DisguisePlugin
author: Albi
description: Disguise Plugin
name: DiguisePlugin
version: 0.1
depend: [ProtocolLib, SkinsRestorer, TagAPI]
commands:
   disguise:
      usage: /<command>
      permissions: disguise
   unmask:
      usage: /<command>
