main: main.DisguisePlugin
author: Albi
description: Disguise Plugin
name: DiguisePlugin
version: 0.1
depend: [ProtocolLib, SkinsRestorer, TagAPI]
api-version: 1.13
commands:
   scydisguise:
      usage: /<command>
      permissions: disguise
   scyunmask:
      usage: /<command>
